baseURL = 'https://yukino-insect.github.io/'
languageCode = 'zh-cn'
title = '我永远喜欢雪之下雪乃'

[params]
  highlightjs = false
  custom_css = [
    "css/chroma-silent.css"
  ]
[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = false
    lineNos = false
